python abstract_tagger.py -nj 20 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 1 --abstract-ngrams 0 -o results2\fg_title_1 | tee results2\fg_title_1_stdout.txt
python abstract_tagger.py -nj 20 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 2 --abstract-ngrams 0 -o results2\fg_title_2 | tee results2\fg_title_2_stdout.txt
python abstract_tagger.py -nj 20 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 3 --abstract-ngrams 0 -o results2\fg_title_3 | tee results2\fg_title_3_stdout.txt

python abstract_tagger.py -nj 20 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 0 --abstract-ngrams 1 -o results2\fg_abstract_1 | tee results2\fg_abstract_1_stdout.txt
python abstract_tagger.py -nj 15 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 0 --abstract-ngrams 2 -o results2\fg_abstract_2 | tee results2\fg_abstract_2_stdout.txt
python abstract_tagger.py -nj 10 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 0 --abstract-ngrams 3 -o results2\fg_abstract_3 | tee results2\fg_abstract_3_stdout.txt

rem python abstract_tagger.py -nj 10 -fsr 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 -tr data\train_old\train_data_old_set_processed.csv -te data\test_old\test_data_old_set_processed.csv --binary-relevance-logistic-regression --title-ngrams 2 --abstract-ngrams 3 -o results2\fg_title_2_abstract_3 | tee results2\fg_title_2_abstract_3_stdout.txt
